# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: locator.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import location_pb2 as location__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='locator.proto',
  package='com.igrow.locator',
  syntax='proto3',
  serialized_pb=_b('\n\rlocator.proto\x12\x11\x63om.igrow.locator\x1a\x0elocation.proto\"a\n\x1a\x42\x65ginLocatorSessionRequest\x12\x10\n\x08\x64\x65viceId\x18\x01 \x01(\t\x12\x31\n\x08location\x18\x02 \x01(\x0b\x32\x1f.com.igrow.observation.Location\"\x84\x02\n\x1b\x42\x65ginLocatorSessionResponse\x12N\n\x0cresponseCode\x18\x01 \x01(\x0e\x32\x38.com.igrow.locator.BeginLocatorSessionResponse.ErrorCode\x12\x17\n\x0fresponseMessage\x18\x02 \x01(\t\x12\x11\n\tsessionId\x18\x03 \x01(\t\"i\n\tErrorCode\x12\x08\n\x04NONE\x10\x00\x12\x12\n\x0eINTERNAL_ERROR\x10\x01\x12\x1b\n\x17SESSION_ALREADY_STARTED\x10\x02\x12!\n\x1dINSUFFICIENT_LOCAL_CANDIDATES\x10\x03\"-\n\x19JoinLocatorSessionRequest\x12\x10\n\x08\x64\x65viceId\x18\x01 \x01(\t\"\xc4\x01\n\x1aJoinLocatorSessionResponse\x12M\n\x0cresponseCode\x18\x01 \x01(\x0e\x32\x37.com.igrow.locator.JoinLocatorSessionResponse.ErrorCode\x12\x17\n\x0fresponseMessage\x18\x02 \x01(\t\">\n\tErrorCode\x12\x08\n\x04NONE\x10\x00\x12\x12\n\x0eINTERNAL_ERROR\x10\x01\x12\x13\n\x0fSESSION_INVALID\x10\x02\",\n\x18\x45ndLocatorSessionRequest\x12\x10\n\x08\x64\x65viceId\x18\x01 \x01(\t\"\xc2\x01\n\x19\x45ndLocatorSessionResponse\x12L\n\x0cresponseCode\x18\x01 \x01(\x0e\x32\x36.com.igrow.locator.EndLocatorSessionResponse.ErrorCode\x12\x17\n\x0fresponseMessage\x18\x02 \x01(\t\">\n\tErrorCode\x12\x08\n\x04NONE\x10\x00\x12\x12\n\x0eINTERNAL_ERROR\x10\x01\x12\x13\n\x0fSESSION_INVALID\x10\x02\x42-\n\x1a\x63om.igrow.protobuf.locatorB\x0fLocatorProtoBufb\x06proto3')
  ,
  dependencies=[location__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_BEGINLOCATORSESSIONRESPONSE_ERRORCODE = _descriptor.EnumDescriptor(
  name='ErrorCode',
  full_name='com.igrow.locator.BeginLocatorSessionResponse.ErrorCode',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='NONE', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='INTERNAL_ERROR', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SESSION_ALREADY_STARTED', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='INSUFFICIENT_LOCAL_CANDIDATES', index=3, number=3,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=307,
  serialized_end=412,
)
_sym_db.RegisterEnumDescriptor(_BEGINLOCATORSESSIONRESPONSE_ERRORCODE)

_JOINLOCATORSESSIONRESPONSE_ERRORCODE = _descriptor.EnumDescriptor(
  name='ErrorCode',
  full_name='com.igrow.locator.JoinLocatorSessionResponse.ErrorCode',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='NONE', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='INTERNAL_ERROR', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SESSION_INVALID', index=2, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=596,
  serialized_end=658,
)
_sym_db.RegisterEnumDescriptor(_JOINLOCATORSESSIONRESPONSE_ERRORCODE)

_ENDLOCATORSESSIONRESPONSE_ERRORCODE = _descriptor.EnumDescriptor(
  name='ErrorCode',
  full_name='com.igrow.locator.EndLocatorSessionResponse.ErrorCode',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='NONE', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='INTERNAL_ERROR', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SESSION_INVALID', index=2, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=596,
  serialized_end=658,
)
_sym_db.RegisterEnumDescriptor(_ENDLOCATORSESSIONRESPONSE_ERRORCODE)


_BEGINLOCATORSESSIONREQUEST = _descriptor.Descriptor(
  name='BeginLocatorSessionRequest',
  full_name='com.igrow.locator.BeginLocatorSessionRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='deviceId', full_name='com.igrow.locator.BeginLocatorSessionRequest.deviceId', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='location', full_name='com.igrow.locator.BeginLocatorSessionRequest.location', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=52,
  serialized_end=149,
)


_BEGINLOCATORSESSIONRESPONSE = _descriptor.Descriptor(
  name='BeginLocatorSessionResponse',
  full_name='com.igrow.locator.BeginLocatorSessionResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='responseCode', full_name='com.igrow.locator.BeginLocatorSessionResponse.responseCode', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='responseMessage', full_name='com.igrow.locator.BeginLocatorSessionResponse.responseMessage', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sessionId', full_name='com.igrow.locator.BeginLocatorSessionResponse.sessionId', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _BEGINLOCATORSESSIONRESPONSE_ERRORCODE,
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=152,
  serialized_end=412,
)


_JOINLOCATORSESSIONREQUEST = _descriptor.Descriptor(
  name='JoinLocatorSessionRequest',
  full_name='com.igrow.locator.JoinLocatorSessionRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='deviceId', full_name='com.igrow.locator.JoinLocatorSessionRequest.deviceId', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=414,
  serialized_end=459,
)


_JOINLOCATORSESSIONRESPONSE = _descriptor.Descriptor(
  name='JoinLocatorSessionResponse',
  full_name='com.igrow.locator.JoinLocatorSessionResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='responseCode', full_name='com.igrow.locator.JoinLocatorSessionResponse.responseCode', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='responseMessage', full_name='com.igrow.locator.JoinLocatorSessionResponse.responseMessage', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _JOINLOCATORSESSIONRESPONSE_ERRORCODE,
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=462,
  serialized_end=658,
)


_ENDLOCATORSESSIONREQUEST = _descriptor.Descriptor(
  name='EndLocatorSessionRequest',
  full_name='com.igrow.locator.EndLocatorSessionRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='deviceId', full_name='com.igrow.locator.EndLocatorSessionRequest.deviceId', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=660,
  serialized_end=704,
)


_ENDLOCATORSESSIONRESPONSE = _descriptor.Descriptor(
  name='EndLocatorSessionResponse',
  full_name='com.igrow.locator.EndLocatorSessionResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='responseCode', full_name='com.igrow.locator.EndLocatorSessionResponse.responseCode', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='responseMessage', full_name='com.igrow.locator.EndLocatorSessionResponse.responseMessage', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _ENDLOCATORSESSIONRESPONSE_ERRORCODE,
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=707,
  serialized_end=901,
)

_BEGINLOCATORSESSIONREQUEST.fields_by_name['location'].message_type = location__pb2._LOCATION
_BEGINLOCATORSESSIONRESPONSE.fields_by_name['responseCode'].enum_type = _BEGINLOCATORSESSIONRESPONSE_ERRORCODE
_BEGINLOCATORSESSIONRESPONSE_ERRORCODE.containing_type = _BEGINLOCATORSESSIONRESPONSE
_JOINLOCATORSESSIONRESPONSE.fields_by_name['responseCode'].enum_type = _JOINLOCATORSESSIONRESPONSE_ERRORCODE
_JOINLOCATORSESSIONRESPONSE_ERRORCODE.containing_type = _JOINLOCATORSESSIONRESPONSE
_ENDLOCATORSESSIONRESPONSE.fields_by_name['responseCode'].enum_type = _ENDLOCATORSESSIONRESPONSE_ERRORCODE
_ENDLOCATORSESSIONRESPONSE_ERRORCODE.containing_type = _ENDLOCATORSESSIONRESPONSE
DESCRIPTOR.message_types_by_name['BeginLocatorSessionRequest'] = _BEGINLOCATORSESSIONREQUEST
DESCRIPTOR.message_types_by_name['BeginLocatorSessionResponse'] = _BEGINLOCATORSESSIONRESPONSE
DESCRIPTOR.message_types_by_name['JoinLocatorSessionRequest'] = _JOINLOCATORSESSIONREQUEST
DESCRIPTOR.message_types_by_name['JoinLocatorSessionResponse'] = _JOINLOCATORSESSIONRESPONSE
DESCRIPTOR.message_types_by_name['EndLocatorSessionRequest'] = _ENDLOCATORSESSIONREQUEST
DESCRIPTOR.message_types_by_name['EndLocatorSessionResponse'] = _ENDLOCATORSESSIONRESPONSE

BeginLocatorSessionRequest = _reflection.GeneratedProtocolMessageType('BeginLocatorSessionRequest', (_message.Message,), dict(
  DESCRIPTOR = _BEGINLOCATORSESSIONREQUEST,
  __module__ = 'locator_pb2'
  # @@protoc_insertion_point(class_scope:com.igrow.locator.BeginLocatorSessionRequest)
  ))
_sym_db.RegisterMessage(BeginLocatorSessionRequest)

BeginLocatorSessionResponse = _reflection.GeneratedProtocolMessageType('BeginLocatorSessionResponse', (_message.Message,), dict(
  DESCRIPTOR = _BEGINLOCATORSESSIONRESPONSE,
  __module__ = 'locator_pb2'
  # @@protoc_insertion_point(class_scope:com.igrow.locator.BeginLocatorSessionResponse)
  ))
_sym_db.RegisterMessage(BeginLocatorSessionResponse)

JoinLocatorSessionRequest = _reflection.GeneratedProtocolMessageType('JoinLocatorSessionRequest', (_message.Message,), dict(
  DESCRIPTOR = _JOINLOCATORSESSIONREQUEST,
  __module__ = 'locator_pb2'
  # @@protoc_insertion_point(class_scope:com.igrow.locator.JoinLocatorSessionRequest)
  ))
_sym_db.RegisterMessage(JoinLocatorSessionRequest)

JoinLocatorSessionResponse = _reflection.GeneratedProtocolMessageType('JoinLocatorSessionResponse', (_message.Message,), dict(
  DESCRIPTOR = _JOINLOCATORSESSIONRESPONSE,
  __module__ = 'locator_pb2'
  # @@protoc_insertion_point(class_scope:com.igrow.locator.JoinLocatorSessionResponse)
  ))
_sym_db.RegisterMessage(JoinLocatorSessionResponse)

EndLocatorSessionRequest = _reflection.GeneratedProtocolMessageType('EndLocatorSessionRequest', (_message.Message,), dict(
  DESCRIPTOR = _ENDLOCATORSESSIONREQUEST,
  __module__ = 'locator_pb2'
  # @@protoc_insertion_point(class_scope:com.igrow.locator.EndLocatorSessionRequest)
  ))
_sym_db.RegisterMessage(EndLocatorSessionRequest)

EndLocatorSessionResponse = _reflection.GeneratedProtocolMessageType('EndLocatorSessionResponse', (_message.Message,), dict(
  DESCRIPTOR = _ENDLOCATORSESSIONRESPONSE,
  __module__ = 'locator_pb2'
  # @@protoc_insertion_point(class_scope:com.igrow.locator.EndLocatorSessionResponse)
  ))
_sym_db.RegisterMessage(EndLocatorSessionResponse)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\032com.igrow.protobuf.locatorB\017LocatorProtoBuf'))
# @@protoc_insertion_point(module_scope)
