# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sensor.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import location_pb2 as location__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='sensor.proto',
  package='com.igrow.sensor',
  syntax='proto3',
  serialized_pb=_b('\n\x0csensor.proto\x12\x10\x63om.igrow.sensor\x1a\x0elocation.proto\"\xa7\x02\n\x06Sensor\x12\x10\n\x08sensorId\x18\x01 \x01(\t\x12\x37\n\nsensorType\x18\x02 \x01(\x0e\x32#.com.igrow.sensor.Sensor.SensorType\x12\x17\n\x0f\x66irmwareVersion\x18\x03 \x01(\t\x12\x10\n\x08nickname\x18\x04 \x01(\t\x12\r\n\x05model\x18\x05 \x01(\t\x12\x0f\n\x07product\x18\x06 \x01(\t\x12:\n\x11lastKnownLocation\x18\x07 \x01(\x0b\x32\x1f.com.igrow.observation.Location\"K\n\nSensorType\x12\r\n\tIGROW_101\x10\x00\x12\x16\n\x12IGROW_TDR_MOISTURE\x10\x01\x12\x16\n\x12IGROW_SPECTROMETER\x10\x02\"A\n\x15RegisterSensorRequest\x12(\n\x06sensor\x18\x01 \x01(\x0b\x32\x18.com.igrow.sensor.Sensor\"\x92\x01\n\x16RegisterSensorResponse\x12H\n\x0cresponseCode\x18\x01 \x01(\x0e\x32\x32.com.igrow.sensor.RegisterSensorResponse.ErrorCode\x12\x17\n\x0fresponseMessage\x18\x02 \x01(\t\"\x15\n\tErrorCode\x12\x08\n\x04NONE\x10\x00\x42+\n\x19\x63om.igrow.protobuf.sensorB\x0eSensorProtoBufb\x06proto3')
  ,
  dependencies=[location__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_SENSOR_SENSORTYPE = _descriptor.EnumDescriptor(
  name='SensorType',
  full_name='com.igrow.sensor.Sensor.SensorType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='IGROW_101', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='IGROW_TDR_MOISTURE', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='IGROW_SPECTROMETER', index=2, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=271,
  serialized_end=346,
)
_sym_db.RegisterEnumDescriptor(_SENSOR_SENSORTYPE)

_REGISTERSENSORRESPONSE_ERRORCODE = _descriptor.EnumDescriptor(
  name='ErrorCode',
  full_name='com.igrow.sensor.RegisterSensorResponse.ErrorCode',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='NONE', index=0, number=0,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=541,
  serialized_end=562,
)
_sym_db.RegisterEnumDescriptor(_REGISTERSENSORRESPONSE_ERRORCODE)


_SENSOR = _descriptor.Descriptor(
  name='Sensor',
  full_name='com.igrow.sensor.Sensor',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sensorId', full_name='com.igrow.sensor.Sensor.sensorId', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sensorType', full_name='com.igrow.sensor.Sensor.sensorType', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='firmwareVersion', full_name='com.igrow.sensor.Sensor.firmwareVersion', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='nickname', full_name='com.igrow.sensor.Sensor.nickname', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='model', full_name='com.igrow.sensor.Sensor.model', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='product', full_name='com.igrow.sensor.Sensor.product', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='lastKnownLocation', full_name='com.igrow.sensor.Sensor.lastKnownLocation', index=6,
      number=7, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _SENSOR_SENSORTYPE,
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=51,
  serialized_end=346,
)


_REGISTERSENSORREQUEST = _descriptor.Descriptor(
  name='RegisterSensorRequest',
  full_name='com.igrow.sensor.RegisterSensorRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sensor', full_name='com.igrow.sensor.RegisterSensorRequest.sensor', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=348,
  serialized_end=413,
)


_REGISTERSENSORRESPONSE = _descriptor.Descriptor(
  name='RegisterSensorResponse',
  full_name='com.igrow.sensor.RegisterSensorResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='responseCode', full_name='com.igrow.sensor.RegisterSensorResponse.responseCode', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='responseMessage', full_name='com.igrow.sensor.RegisterSensorResponse.responseMessage', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _REGISTERSENSORRESPONSE_ERRORCODE,
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=416,
  serialized_end=562,
)

_SENSOR.fields_by_name['sensorType'].enum_type = _SENSOR_SENSORTYPE
_SENSOR.fields_by_name['lastKnownLocation'].message_type = location__pb2._LOCATION
_SENSOR_SENSORTYPE.containing_type = _SENSOR
_REGISTERSENSORREQUEST.fields_by_name['sensor'].message_type = _SENSOR
_REGISTERSENSORRESPONSE.fields_by_name['responseCode'].enum_type = _REGISTERSENSORRESPONSE_ERRORCODE
_REGISTERSENSORRESPONSE_ERRORCODE.containing_type = _REGISTERSENSORRESPONSE
DESCRIPTOR.message_types_by_name['Sensor'] = _SENSOR
DESCRIPTOR.message_types_by_name['RegisterSensorRequest'] = _REGISTERSENSORREQUEST
DESCRIPTOR.message_types_by_name['RegisterSensorResponse'] = _REGISTERSENSORRESPONSE

Sensor = _reflection.GeneratedProtocolMessageType('Sensor', (_message.Message,), dict(
  DESCRIPTOR = _SENSOR,
  __module__ = 'sensor_pb2'
  # @@protoc_insertion_point(class_scope:com.igrow.sensor.Sensor)
  ))
_sym_db.RegisterMessage(Sensor)

RegisterSensorRequest = _reflection.GeneratedProtocolMessageType('RegisterSensorRequest', (_message.Message,), dict(
  DESCRIPTOR = _REGISTERSENSORREQUEST,
  __module__ = 'sensor_pb2'
  # @@protoc_insertion_point(class_scope:com.igrow.sensor.RegisterSensorRequest)
  ))
_sym_db.RegisterMessage(RegisterSensorRequest)

RegisterSensorResponse = _reflection.GeneratedProtocolMessageType('RegisterSensorResponse', (_message.Message,), dict(
  DESCRIPTOR = _REGISTERSENSORRESPONSE,
  __module__ = 'sensor_pb2'
  # @@protoc_insertion_point(class_scope:com.igrow.sensor.RegisterSensorResponse)
  ))
_sym_db.RegisterMessage(RegisterSensorResponse)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\031com.igrow.protobuf.sensorB\016SensorProtoBuf'))
# @@protoc_insertion_point(module_scope)
